<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190729142134 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE account CHANGE account_source account_source VARCHAR(255) DEFAULT NULL, CHANGE annual_revenue annual_revenue DOUBLE PRECISION DEFAULT NULL, CHANGE billing_city billing_city VARCHAR(255) DEFAULT NULL, CHANGE billing_country billing_country VARCHAR(255) DEFAULT NULL, CHANGE billing_geocode_accuracy billing_geocode_accuracy VARCHAR(255) DEFAULT NULL, CHANGE billing_latitude billing_latitude DOUBLE PRECISION DEFAULT NULL, CHANGE billing_longitude billing_longitude DOUBLE PRECISION DEFAULT NULL, CHANGE billing_postal_code billing_postal_code VARCHAR(255) DEFAULT NULL, CHANGE billing_state billing_state VARCHAR(255) DEFAULT NULL, CHANGE billing_street billing_street VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE fax fax VARCHAR(255) DEFAULT NULL, CHANGE industry industry VARCHAR(255) DEFAULT NULL, CHANGE jigsaw jigsaw VARCHAR(255) DEFAULT NULL, CHANGE number_of_employees number_of_employees INT DEFAULT NULL, CHANGE owner_id owner_id VARCHAR(255) DEFAULT NULL, CHANGE parent_id parent_id VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE shipping_city shipping_city VARCHAR(255) DEFAULT NULL, CHANGE shipping_country shipping_country VARCHAR(255) DEFAULT NULL, CHANGE shipping_geocode_accuracy shipping_geocode_accuracy VARCHAR(255) DEFAULT NULL, CHANGE shipping_latitude shipping_latitude DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_longitude shipping_longitude DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_postal_code shipping_postal_code VARCHAR(255) DEFAULT NULL, CHANGE shipping_state shipping_state VARCHAR(255) DEFAULT NULL, CHANGE shipping_street shipping_street VARCHAR(255) DEFAULT NULL, CHANGE sic_desc sic_desc VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE website website VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE contract CHANGE account_id account_id VARCHAR(255) DEFAULT NULL, CHANGE activated_by_id activated_by_id VARCHAR(255) DEFAULT NULL, CHANGE activated_date activated_date VARCHAR(255) DEFAULT NULL, CHANGE billing_city billing_city VARCHAR(255) DEFAULT NULL, CHANGE billing_country billing_country VARCHAR(255) DEFAULT NULL, CHANGE billing_geocode_accuracy billing_geocode_accuracy VARCHAR(255) DEFAULT NULL, CHANGE billing_latitude billing_latitude DOUBLE PRECISION DEFAULT NULL, CHANGE billing_longitude billing_longitude DOUBLE PRECISION DEFAULT NULL, CHANGE billing_postal_code billing_postal_code VARCHAR(255) DEFAULT NULL, CHANGE billing_state billing_state VARCHAR(255) DEFAULT NULL, CHANGE billing_street billing_street VARCHAR(255) DEFAULT NULL, CHANGE company_signed_date company_signed_date VARCHAR(255) DEFAULT NULL, CHANGE company_signed_id company_signed_id VARCHAR(255) DEFAULT NULL, CHANGE contract_term contract_term INT DEFAULT NULL, CHANGE customer_signed_date customer_signed_date VARCHAR(255) DEFAULT NULL, CHANGE customer_signed_id customer_signed_id VARCHAR(255) DEFAULT NULL, CHANGE customer_signed_title customer_signed_title VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE owner_expiration_notice owner_expiration_notice VARCHAR(255) DEFAULT NULL, CHANGE owner_id owner_id VARCHAR(255) DEFAULT NULL, CHANGE shipping_city shipping_city VARCHAR(255) DEFAULT NULL, CHANGE shipping_country shipping_country VARCHAR(255) DEFAULT NULL, CHANGE shipping_geocode_accuracy shipping_geocode_accuracy VARCHAR(255) DEFAULT NULL, CHANGE shipping_latitude shipping_latitude DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_longitude shipping_longitude DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_postal_code shipping_postal_code VARCHAR(255) DEFAULT NULL, CHANGE shipping_state shipping_state VARCHAR(255) DEFAULT NULL, CHANGE shipping_street shipping_street VARCHAR(255) DEFAULT NULL, CHANGE special_terms special_terms VARCHAR(255) DEFAULT NULL, CHANGE start_date start_date VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE `order` CHANGE account_id account_id VARCHAR(255) DEFAULT NULL, CHANGE owner_id owner_id VARCHAR(255) DEFAULT NULL, CHANGE pricebook2id pricebook2id VARCHAR(255) DEFAULT NULL, CHANGE activated_by_id activated_by_id VARCHAR(255) DEFAULT NULL, CHANGE activated_date activated_date VARCHAR(255) DEFAULT NULL, CHANGE billing_city billing_city VARCHAR(255) DEFAULT NULL, CHANGE billing_country billing_country VARCHAR(255) DEFAULT NULL, CHANGE billing_geocode_accuracy billing_geocode_accuracy VARCHAR(255) DEFAULT NULL, CHANGE billing_latitude billing_latitude DOUBLE PRECISION DEFAULT NULL, CHANGE billing_longitude billing_longitude DOUBLE PRECISION DEFAULT NULL, CHANGE billing_postal_code billing_postal_code VARCHAR(255) DEFAULT NULL, CHANGE billing_state billing_state VARCHAR(255) DEFAULT NULL, CHANGE billing_street billing_street VARCHAR(255) DEFAULT NULL, CHANGE company_authorized_by_id company_authorized_by_id VARCHAR(255) DEFAULT NULL, CHANGE contract_id contract_id VARCHAR(255) DEFAULT NULL, CHANGE customer_authorized_by_id customer_authorized_by_id VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE effective_date effective_date VARCHAR(255) DEFAULT NULL, CHANGE end_date end_date VARCHAR(255) DEFAULT NULL, CHANGE shipping_city shipping_city VARCHAR(255) DEFAULT NULL, CHANGE shipping_country shipping_country VARCHAR(255) DEFAULT NULL, CHANGE shipping_geocode_accuracy shipping_geocode_accuracy VARCHAR(255) DEFAULT NULL, CHANGE shipping_latitude shipping_latitude DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_longitude shipping_longitude DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_postal_code shipping_postal_code VARCHAR(255) DEFAULT NULL, CHANGE shipping_state shipping_state VARCHAR(255) DEFAULT NULL, CHANGE shipping_street shipping_street VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE status_code status_code VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE account CHANGE account_source account_source VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE annual_revenue annual_revenue DOUBLE PRECISION NOT NULL, CHANGE billing_city billing_city VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_country billing_country VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_geocode_accuracy billing_geocode_accuracy VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_latitude billing_latitude DOUBLE PRECISION NOT NULL, CHANGE billing_longitude billing_longitude DOUBLE PRECISION NOT NULL, CHANGE billing_postal_code billing_postal_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_state billing_state VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_street billing_street VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE description description VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE fax fax VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE industry industry VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE jigsaw jigsaw VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE number_of_employees number_of_employees INT NOT NULL, CHANGE owner_id owner_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE parent_id parent_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE phone phone VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_city shipping_city VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_country shipping_country VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_geocode_accuracy shipping_geocode_accuracy VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_latitude shipping_latitude DOUBLE PRECISION NOT NULL, CHANGE shipping_longitude shipping_longitude DOUBLE PRECISION NOT NULL, CHANGE shipping_postal_code shipping_postal_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_state shipping_state VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_street shipping_street VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE sic_desc sic_desc VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE type type VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE website website VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE contract CHANGE account_id account_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE activated_by_id activated_by_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE activated_date activated_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_city billing_city VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_country billing_country VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_geocode_accuracy billing_geocode_accuracy VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_latitude billing_latitude DOUBLE PRECISION NOT NULL, CHANGE billing_longitude billing_longitude DOUBLE PRECISION NOT NULL, CHANGE billing_postal_code billing_postal_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_state billing_state VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_street billing_street VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE company_signed_date company_signed_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE company_signed_id company_signed_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE contract_term contract_term INT NOT NULL, CHANGE customer_signed_date customer_signed_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE customer_signed_id customer_signed_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE customer_signed_title customer_signed_title VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE description description VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE owner_expiration_notice owner_expiration_notice VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE owner_id owner_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_city shipping_city VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_country shipping_country VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_geocode_accuracy shipping_geocode_accuracy VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_latitude shipping_latitude DOUBLE PRECISION NOT NULL, CHANGE shipping_longitude shipping_longitude DOUBLE PRECISION NOT NULL, CHANGE shipping_postal_code shipping_postal_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_state shipping_state VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_street shipping_street VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE special_terms special_terms VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE start_date start_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE status status VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE `order` CHANGE account_id account_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE owner_id owner_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE pricebook2id pricebook2id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE activated_by_id activated_by_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE activated_date activated_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_city billing_city VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_country billing_country VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_geocode_accuracy billing_geocode_accuracy VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_latitude billing_latitude DOUBLE PRECISION NOT NULL, CHANGE billing_longitude billing_longitude DOUBLE PRECISION NOT NULL, CHANGE billing_postal_code billing_postal_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_state billing_state VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE billing_street billing_street VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE company_authorized_by_id company_authorized_by_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE contract_id contract_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE customer_authorized_by_id customer_authorized_by_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE description description VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE effective_date effective_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE end_date end_date VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_city shipping_city VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_country shipping_country VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_geocode_accuracy shipping_geocode_accuracy VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_latitude shipping_latitude DOUBLE PRECISION NOT NULL, CHANGE shipping_longitude shipping_longitude DOUBLE PRECISION NOT NULL, CHANGE shipping_postal_code shipping_postal_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_state shipping_state VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE shipping_street shipping_street VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE status status VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE status_code status_code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE type type VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci');
    }
}
